version: 2
jobs:
  build:
    docker:
      - image: ruby:2.5.3
    steps:
      - run:
          name: Install dependencies
          command: |
            echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list
            curl -s https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            apt-get update -qq
            apt-get install -y --no-install-recommends build-essential libpq-dev nodejs google-chrome-stable
            wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(google-chrome-stable --version | cut -d ' ' -f 3 | cut -d . -f 1))/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip -d /usr/bin/ > /dev/null

      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install all dependencies in Gemfile
          command: |
            bundle install
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle

      - run:
          name: Setup DB
          command: |
            rails db:setup

      - run:
          name: Test vulnerabilities
          command: |
            rails training
