version: 2
jobs:
  build:
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - checkout
      - run:
            name: Build Docker image
            command: |
                 docker-compose build
  test:
    steps:
      - checkout
      - run:
            name: Copy volume into Docker container
            command: |
                 docker cp . $(docker-compose ps -q):/myapp
      - run:
            name: Setup DB
            command: |
                 docker-compose run web rails db:setup
      - run:
            name: Vulnerability test
            command: |
                 docker-compose run web rails training
