version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
            name: Build Docker image
            command: |
                 docker-compose build
      - run:
            name: Create Docker container
            command: |
                 docker-compose up --no-start
      - run:
            name: Copy volume into Docker container
            command: |
                 docker cp . $(docker-compose ps -q):/myapp
      - run:
            name: Start Docker container
            command: |
                 docker-compose start
      - run:
            name: Setup DB
            command: |
                 docker-compose exec web rails db:setup
      - run:
            name: Vulnerability test
            command: |
                 docker-compose exec web rails training
